export default {
    ContinueButton: "Continue",
    WhenIsYourBabyDue: "When is your baby due, %{name}?",
    ForAFitAndRelaxedPregnancy: "For a fit and relaxed pregnancy",
    GetStartedButton: "Get Started",
    OrLoginButton: "Or login",
    LoginButton: "Log in",
    ItsGreatThatYoureHere: "It's great that you're here! First things first, what should we call you?",
    YourNamePlaceholder: "Your Name",
    WelcomeBack: "Welcome back!",
    HaveYouForgottenYourPassword: "Have you forgotten your password?",
    ExampleEmailPlaceholder: "example@gmail.com",
    EnterPasswordPlaceholder: "Enter a password",
    AddYourDetailsTitle: "Add your details below to set up an account",
    IveReadThe: "I've read the ",
    PrivacyPolicy: "privacy policy",
    IAcceptThe: "I accept the ",
    TermsAndConditions: "terms & conditions", 
    And: " and ", 
    KeleyasAdvice: "Keleya's advice",
    GetNotificationsTitle: "Get notifications to boost your motivation",
    SkipButton: "Skip",
    AllowNotificationsButton: "Allow notifications",
    HowManyTimesAWeek: "How many times a week do you want to be active?",
    WeeksPerDay: [
        "Once a week",
        "2 times a week",
        "3 times a week",
        "4 times a week",
        "5 times a week",
        "6 times a week",
        "7 times a week",
      ],
    
  };
  